baseurl      = "purabparihar.github.io"
title        = "Purab Parihar"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"
enableEmoji        = true
enableGitInfo      = true

PygmentsCodeFences = true
PygmentsStyle      = "native"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006"
  images = "/images/logo.png"
  # Subtitle for home
  homeSubtitle = "A blog about Offensive Security to share my Learnings and Knowledge"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "A blog about Offensive Security to share my Learnings and Knowledge"
  keywords = "homepage, blog, red teaming, cybersecurity, penetration testing, purab parihar"
  contentTypeName = "posts"
  enableThemeToggle = true
  defaultTheme = "dark"

[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/purab_parihar"

 [[params.social]]
    name = "email"
    url  = "mailto:purabpariha21@gmail.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/purabparihar/"

[params.footer]
    trademark = false
    rss = true
    copyright = true
    author = false

    topText = []
    bottomText = [
      "<a href=\"http://gohugo.io\">Hugo</a> theme by <a href=\"https://github.com/rhazdon\">rhazdon</a>"
    ]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Purab Parihar"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Security Blogs"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[permalinks]
  posts = "/posts/:title/"